sudo: required
services:
  - docker

before_install:
  - docker build -t yannicksealy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run yannicksealy/react-test npm test -- --coverage

after_success:
  - docker build -t yannicksealy/multi-client ./client
  - docker build -t yannicksealy/multi-nginx ./nginx
  - docker build -t yannicksealy/multi-server ./server
  - docker build -t yannicksealy/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yannicksealy/multi-client
  - docker push yannicksealy/multi-nginx
  - docker push yannicksealy/multi-server
  - docker push yannicksealy/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-521418590951
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY



